apiVersion: v1
kind: Secret
metadata:
  name: creds
  namespace: crossplane
type: Opaque
stringData:
  credentials: |
    {
      "access_key": "",
      "secret_key": "",
      "region": "cn-beijing"
    }
